// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDwhwGMyYweeAb1krnoMeIgChDOCqitjYs',
    appId: '1:557499886499:web:0472b48f43be4c32ea4816',
    messagingSenderId: '557499886499',
    projectId: 'bmi-app-ab16e',
    authDomain: 'bmi-app-ab16e.firebaseapp.com',
    storageBucket: 'bmi-app-ab16e.firebasestorage.app',
    measurementId: 'G-4YN5ET6M85',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBE9YzvXRThMcpriw0HbISO0yCsIqGQO9Q',
    appId: '1:557499886499:android:616bbdf281ca25aaea4816',
    messagingSenderId: '557499886499',
    projectId: 'bmi-app-ab16e',
    storageBucket: 'bmi-app-ab16e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCrdmNmIZl5mXQsFl2q4yOPZ-xxXzVCgUc',
    appId: '1:557499886499:ios:3cc29a6a56b8c4b1ea4816',
    messagingSenderId: '557499886499',
    projectId: 'bmi-app-ab16e',
    storageBucket: 'bmi-app-ab16e.firebasestorage.app',
    iosBundleId: 'com.example.bmiCalculator',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCrdmNmIZl5mXQsFl2q4yOPZ-xxXzVCgUc',
    appId: '1:557499886499:ios:3cc29a6a56b8c4b1ea4816',
    messagingSenderId: '557499886499',
    projectId: 'bmi-app-ab16e',
    storageBucket: 'bmi-app-ab16e.firebasestorage.app',
    iosBundleId: 'com.example.bmiCalculator',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDwhwGMyYweeAb1krnoMeIgChDOCqitjYs',
    appId: '1:557499886499:web:83e6a6c16d072264ea4816',
    messagingSenderId: '557499886499',
    projectId: 'bmi-app-ab16e',
    authDomain: 'bmi-app-ab16e.firebaseapp.com',
    storageBucket: 'bmi-app-ab16e.firebasestorage.app',
    measurementId: 'G-682M8V5VTQ',
  );

}